<?php

return [

    'Ogrenci' => [
        ['#' => 'id'],
        ['Kategori' => 'kategori'],
        ['Ad Soyad' => 'ad_soyad'],
        ['TC' => 'tc'],
        ['Baba Adı' => 'baba_adi'],
        ['Doğum Tarihi' => 'dogum_tarihi|date'],
        ['Telefon' => 'telefon'],
        ['Doğum Yeri' => 'dogum_yeri'],
        ['Adres' => 'adres'],
        ['E-posta' => 'email'],
        ['Bölüm' => 'bolum'],
        ['Öğrenci Belgesi' => 'file:ogrenci_belgesi'],
        ['Vesikalık' => 'file:vesikalik'],
        ['KVKK Onay' => 'badge:aydinlatma_onay'],
        ['Durum' => 'badge:durum'],
    ],

    'Ogretmen' => [
        ['#' => 'id'],
        ['Kategori' => 'kategori'],
        ['Ad Soyad' => 'ad_soyad'],
        ['TC' => 'tc'],
        ['Branş' => 'meta.brans'],
        ['Okul' => 'meta.okul'],
        ['Telefon' => 'telefon'],
        ['E-posta' => 'email'],
        ['Vesikalık' => 'file:vesikalik'],
        ['Durum' => 'badge:durum'],
    ],

    'Emniyet' => [
        ['#' => 'id'],
        ['Kategori' => 'kategori'],
        ['Ad Soyad' => 'ad_soyad'],
        ['TC' => 'tc'],
        ['Baba Adı' => 'baba_adi'],
        ['Doğum Tarihi' => 'dogum_tarihi|date'],
        ['Telefon' => 'telefon'],
        ['Doğum Yeri' => 'dogum_yeri'],
        ['Adres' => 'adres'],
        ['E-posta' => 'email'],
        ['Emniyet Belgesi (PDF)' => 'file:belediye_yazi'],
        ['Vesikalık' => 'file:vesikalik'],
        ['Durum' => 'badge:durum'],
    ],

    'Jandarma' => [
        ['#' => 'id'],
        ['Kategori' => 'kategori'],
        ['Ad Soyad' => 'ad_soyad'],
        ['TC' => 'tc'],
        ['Baba Adı' => 'baba_adi'],
        ['Doğum Tarihi' => 'dogum_tarihi|date'],
        ['Telefon' => 'telefon'],
        ['Doğum Yeri' => 'dogum_yeri'],
        ['Adres' => 'adres'],
        ['E-posta' => 'email'],
        ['Jandarma Belgesi (PDF)' => 'file:belediye_yazi'],
        ['Vesikalık' => 'file:vesikalik'],
        ['Durum' => 'badge:durum'],
    ],

    'Belediye' => [
        ['#' => 'id'],
        ['Kategori' => 'kategori'],
        ['Ad Soyad' => 'ad_soyad'],
        ['TC' => 'tc'],
        ['Baba Adı' => 'baba_adi'],
        ['Doğum Tarihi' => 'dogum_tarihi|date'],
        ['Telefon' => 'telefon'],
        ['Doğum Yeri' => 'dogum_yeri'],
        ['Adres' => 'adres'],
        ['E-posta' => 'email'],
        ['Belediye Yazısı (PDF)' => 'file:belediye_yazi'],
        ['Vesikalık' => 'file:vesikalik'],
        ['Durum' => 'badge:durum'],
    ],

    'Gazi' => [
        ['#' => 'id'],
        ['Kategori' => 'kategori'],
        ['Ad Soyad' => 'ad_soyad'],
        ['TC' => 'tc'],
        ['Baba Adı' => 'baba_adi'],
        ['Doğum Tarihi' => 'dogum_tarihi|date'],
        ['Telefon' => 'telefon'],
        ['Doğum Yeri' => 'dogum_yeri'],
        ['Adres' => 'adres'],
        ['E-posta' => 'email'],
        ['Gazi Belgesi (PDF)' => 'file:belediye_yazi'],
        ['Vesikalık' => 'file:vesikalik'],
        ['Durum' => 'badge:durum'],
    ],

    'Sehit' => [
        ['#' => 'id'],
        ['Kategori' => 'kategori'],
        ['Ad Soyad' => 'ad_soyad'],
        ['TC' => 'tc'],
        ['Baba Adı' => 'baba_adi'],
        ['Doğum Tarihi' => 'dogum_tarihi|date'],
        ['Telefon' => 'telefon'],
        ['Doğum Yeri' => 'dogum_yeri'],
        ['Adres' => 'adres'],
        ['E-posta' => 'email'],
        ['Şehit Yakını Belgesi (PDF)' => 'file:belediye_yazi'],
        ['Vesikalık' => 'file:vesikalik'],
        ['Durum' => 'badge:durum'],
    ],

    // Filtre yoksa tümü için geniş görünüm
    'default' => [
        ['#' => 'id'],
        ['Kategori' => 'kategori'],
        ['Ad Soyad' => 'ad_soyad'],
        ['TC' => 'tc'],
        ['Baba Adı' => 'baba_adi'],
        ['Doğum Tarihi' => 'dogum_tarihi|date'],
        ['Doğum Yeri' => 'dogum_yeri'],
        ['Telefon' => 'telefon'],
        ['Adres' => 'adres'],
        ['E-posta' => 'email'],
        ['Bölüm' => 'bolum'],
        ['Öğrenci Belgesi' => 'file:ogrenci_belgesi'],
        ['Belediye/Belge (PDF)' => 'file:belediye_yazi'],
        ['Vesikalık' => 'file:vesikalik'],
        // ['Kimlik Ön' => 'file:kimlik_on'],
        // ['Kimlik Arka' => 'file:kimlik_arka'],
        ['Sicil' => 'sicil'],
        ['Durum' => 'badge:durum'],
    ],
];
